### ISSUE TITLE
[Feature Request] Admin logger logging to admin logger log.

### ISSUE THREAD

**Issue by MisterRee** [BobDaRoss/AdminLogger#1]
Torch Logs are already very full with the output of multiple plugins.

To make this plugin more useful, it would be great if it wrote the relevant information to it's own log so a quick check could be done rather than molesting the mouse scroller to get through the redundant log traffic.

**Comment by LordTylus** [comment]
you actually can set a separate log up yourself right now using the NLog-User config file.

**Comment by Casimir255** [comment]
This has been added
